site_name: Epidemiology and Modelling, University of Cambridge
theme: readthedocs

nav:
- Home: index.md
- Research: research.md
- Interactive projects: interactive.md
- Lab members: people.md
# - News: news.md

