extra_css: [extra.css]

site_name: Epidemiology and Modelling, University of Cambridge
theme: readthedocs

nav:
- Home: index.md
- Transdisciplinary Research Programmes:
  - Cassava: 'research/cassava.md'
  - Wheat Rust: 'research/wheat_rust.md'
  - Locust: 'research/locusts.md'
  - BBTV: 'research/bbtv.md'
- Multi-disciplinary Research Projects: 'research/multidisciplinary_research_programmes.md'
- Discovery Science: 'research/discovery_science.md'
- Computing: 'research/computing.md'
- Impact and Engagement: 'research/impact_and_engagement.md'
- The Team: people.md
- Partners: partners.md
- News: news.md

